version: 2.1
orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@3.3.0

jobs:
  release:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - run:
          name: Release New Version
          command: |
            RELEASE_VERSION=$(node -p -e "require('./package.json').version")
            echo "Releasing version $RELEASE_VERSION"

            # setup git
            git config user.name "Release Script"
            git config user.email "contact@abourdin.com"

            # tag release version
            git tag "release-$RELEASE_VERSION"
            git push origin master --tags

            # prepare development branch
            git fetch
            git checkout develop
            npm version minor -m "Prepared branch for next development iteration"
            git push origin develop
            git checkout -

  prepare-dependencies:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Redis
          command: |
            sudo apt update
            sudo apt install redis-server
      - run:
          name: Create Results Directory
          command: |
            mkdir -p ./test-results/mocha
      - run:
          name: Run tests
          command: npm run test
          timeout: 600
      - codecov/upload:
          file: coverage/*.json
      - store_test_results:
          path: test-results

  dry-run-docs:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Dry-run doc generation
          command: npm run docs
          timeout: 60

  publish:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Package Project
          command: npm run package
      - run:
          name: Generate JSDoc
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config user.name "Release Script"
            git config user.email "contact@abourdin.com"

            git checkout -B docs

            npm run docs
            git add docs/* && git commit -m "Updating JSDoc"
            git push -f origin docs
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > build/package/.npmrc
      - run:
          name: Publish Project
          command: |
            cd build/package
            npm publish

workflows:
  build-test:
    jobs:
      - prepare-dependencies:
          filters:
            branches:
              ignore:
                - master
                - docs
      - build:
          requires:
            - prepare-dependencies
      - test:
          requires:
            - prepare-dependencies
      - dry-run-docs:
          requires:
            - prepare-dependencies
  build-test-publish:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
      - prepare-dependencies:
          requires:
            - release
      - build:
          requires:
            - prepare-dependencies
      - test:
          requires:
            - prepare-dependencies
      - publish:
          requires:
            - build
            - test
